CREATE TABLE post (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    author INT UNSIGNED NOT NULL,
    post VARCHAR(255) NOT NULL,
    type ENUM('text', 'image', 'video') NOT NULL,
    date_posted DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(author) REFERENCES user(id) ON DELETE CASCADE
);
