CREATE TABLE post_comment (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    post_id INT UNSIGNED NOT NULL,
    author INT UNSIGNED NOT NULL,
    reply_to INT UNSIGNED,
    comment VARCHAR(255) NOT NULL,
    date_commented DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(post_id) REFERENCES post(id) ON DELETE CASCADE,
    FOREIGN KEY(author) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY(reply_to) REFERENCES post_comment(id) ON DELETE CASCADE
);
